{% set version = "4.1.1" %}

package:
  name: gems3k
  version: {{ version }}

source:
  url: https://github.com/gemshub/GEMS3K/archive/v{{ version }}.tar.gz
  sha256: 3befc97faf81f306dd16a73da11c3314cf84373c704825c897db4932d0a5f817

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - nlohmann_json
    - zeromq
    - cppzmq

test:
  commands:
    - test -d ${PREFIX}/include/GEMS3K  # [unix]
    - test -f ${PREFIX}/include/GEMS3K/node.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GEMS3K\node.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/gemshub/GEMS3K
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Numerical kernel solver of the GEM-Selektor v.3 package for geochemical modelling.
  doc_url: https://github.com/gemshub/GEMS3K
  dev_url: https://github.com/gemshub/GEMS3K

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
