{% set version = "4.3.2" %}

package:
  name: gems3k
  version: {{ version }}

source:
  url: https://github.com/gemshub/GEMS3K/archive/v{{ version }}.tar.gz
  sha256: 1d9b1e22061dcbd5581027b77b53b0f376bdb6681ea89962e7560341484aab92

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make
  host:
    - zeromq
    - cppzmq
    - thermofun =0.4.1

test:
  commands:
    - test -d ${PREFIX}/include/GEMS3K  # [unix]
    - test -f ${PREFIX}/include/GEMS3K/node.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GEMS3K\node.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/gemshub/GEMS3K
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Numerical kernel solver of the GEM-Selektor v.3 package for geochemical modelling.
  doc_url: https://github.com/gemshub/GEMS3K
  dev_url: https://github.com/gemshub/GEMS3K

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
