{% set version = "4.4.2" %}

package:
  name: gems3k
  version: {{ version }}

source:
  url: https://github.com/gemshub/GEMS3K/archive/v{{ version }}.tar.gz
  sha256: 9c344143e1e34fb72c506fd1c8e229c0b7d4fda573d35efc410c28308ba66615

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [win]
    - make
  host:
    - pybind11
    - python
    - pip
    - zeromq
    - cppzmq
    - spdlog >=1.10.0
    - chemicalfun >=0.1.12
    - thermofun >=0.5.2
  run:
    - python
    - pip
    - zeromq
    - cppzmq
    - spdlog >=1.10.0
    - chemicalfun >=0.1.12
    - thermofun >=0.5.2

test:
  commands:
    - test -d ${PREFIX}/include/GEMS3K  # [unix]
    - test -f ${PREFIX}/include/GEMS3K/node.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GEMS3K\node.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/gemshub/GEMS3K
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Numerical kernel solver of the GEM-Selektor v.3 package for geochemical modelling.
  doc_url: https://github.com/gemshub/GEMS3K
  dev_url: https://github.com/gemshub/GEMS3K

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
